import 'dart:io';
import 'dart:typed_data';

import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../features/meetings/domain/entities/meeting.dart';
import '../../features/meetings/domain/entities/meeting_summary.dart';

enum SummaryExportFormat { markdown, word, pdf }

/// Turns a generated [MeetingSummary] into a shareable file — SRD FR-5.4
/// ("view, edit, and export generated summaries") and PHASES.md Phase
/// 12's "Export features: PDF, Word, Markdown." Entirely client-side:
/// there's no backend export endpoint, so this formats data the app
/// already has rather than calling out for a server-rendered document.
///
/// "Word" is produced as RTF rather than a real `.docx` — RTF is a
/// simple, well-documented text format that Word (and Google Docs, and
/// every other word processor) opens natively, and hand-building a
/// correct OOXML `.docx` isn't worth the complexity for what's
/// fundamentally the same plain-text content as the Markdown export.
/// See PHASE12_README.md's known simplifications.
class SummaryExportService {
  const SummaryExportService();

  Future<File> export(Meeting meeting, MeetingSummary summary, SummaryExportFormat format) async {
    switch (format) {
      case SummaryExportFormat.markdown:
        return _writeToTempFile('${_fileBaseName(meeting)}.md', _buildMarkdown(meeting, summary));
      case SummaryExportFormat.word:
        return _writeToTempFile('${_fileBaseName(meeting)}.rtf', _buildRtf(meeting, summary));
      case SummaryExportFormat.pdf:
        final bytes = await _buildPdf(meeting, summary);
        return _writeBytesToTempFile('${_fileBaseName(meeting)}.pdf', bytes);
    }
  }

  String _fileBaseName(Meeting meeting) {
    final safeTitle = meeting.title.replaceAll(RegExp(r'[^a-zA-Z0-9]+'), '-').toLowerCase();
    return 'meetmind-${safeTitle.isEmpty ? 'meeting' : safeTitle}';
  }

  String _buildMarkdown(Meeting meeting, MeetingSummary summary) {
    final buffer = StringBuffer()
      ..writeln('# ${meeting.title}')
      ..writeln()
      ..writeln('_${_formatDate(meeting.date)}${meeting.time != null ? ' · ${meeting.time}' : ''}_')
      ..writeln()
      ..writeln('## Executive summary')
      ..writeln()
      ..writeln(summary.executiveSummary)
      ..writeln();

    _writeMarkdownSection(buffer, 'Key points', summary.bulletSummary);
    _writeMarkdownSection(buffer, 'Decisions', summary.decisions);
    _writeMarkdownSection(buffer, 'Risks', summary.risks);
    _writeMarkdownSection(buffer, 'Next steps', summary.nextSteps);
    _writeMarkdownSection(buffer, 'Deadlines', summary.deadlines);

    buffer
      ..writeln('---')
      ..writeln('_Generated by MeetMind AI_');

    return buffer.toString();
  }

  void _writeMarkdownSection(StringBuffer buffer, String title, List<String> items) {
    if (items.isEmpty) return;
    buffer.writeln('## $title');
    buffer.writeln();
    for (final item in items) {
      buffer.writeln('- $item');
    }
    buffer.writeln();
  }

  String _buildRtf(Meeting meeting, MeetingSummary summary) {
    // Minimal, hand-written RTF — plain content wrapped in the smallest
    // valid RTF header/footer, escaping the three characters RTF treats
    // specially (backslash and the curly braces).
    String esc(String s) => s.replaceAll('\\', '\\\\').replaceAll('{', '\\{').replaceAll('}', '\\}');

    final buffer = StringBuffer()
      ..write(r'{\rtf1\ansi\deff0{\fonttbl{\f0 Calibri;}}')
      ..write(r'\f0\fs28\b ')
      ..write(esc(meeting.title))
      ..write(r'\b0\fs20\par\par')
      ..write(esc('${_formatDate(meeting.date)}${meeting.time != null ? ' - ${meeting.time}' : ''}'))
      ..write(r'\par\par')
      ..write(r'\fs24\b Executive summary\b0\fs20\par')
      ..write(esc(summary.executiveSummary))
      ..write(r'\par\par');

    _writeRtfSection(buffer, 'Key points', summary.bulletSummary, esc);
    _writeRtfSection(buffer, 'Decisions', summary.decisions, esc);
    _writeRtfSection(buffer, 'Risks', summary.risks, esc);
    _writeRtfSection(buffer, 'Next steps', summary.nextSteps, esc);
    _writeRtfSection(buffer, 'Deadlines', summary.deadlines, esc);

    buffer.write(r'}');
    return buffer.toString();
  }

  void _writeRtfSection(StringBuffer buffer, String title, List<String> items, String Function(String) esc) {
    if (items.isEmpty) return;
    buffer.write(r'\fs24\b ');
    buffer.write(esc(title));
    buffer.write(r'\b0\fs20\par');
    for (final item in items) {
      buffer.write(r'\bullet  ');
      buffer.write(esc(item));
      buffer.write(r'\par');
    }
    buffer.write(r'\par');
  }

  Future<Uint8List> _buildPdf(Meeting meeting, MeetingSummary summary) async {
    final doc = pw.Document();

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (context) => [
          pw.Text(meeting.title, style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 4),
          pw.Text(
            '${_formatDate(meeting.date)}${meeting.time != null ? ' · ${meeting.time}' : ''}',
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
          ),
          pw.SizedBox(height: 16),
          pw.Text('Executive summary', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 4),
          pw.Text(summary.executiveSummary),
          pw.SizedBox(height: 16),
          ..._pdfSection('Key points', summary.bulletSummary),
          ..._pdfSection('Decisions', summary.decisions),
          ..._pdfSection('Risks', summary.risks),
          ..._pdfSection('Next steps', summary.nextSteps),
          ..._pdfSection('Deadlines', summary.deadlines),
          pw.SizedBox(height: 16),
          pw.Divider(),
          pw.Text('Generated by MeetMind AI', style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600)),
        ],
      ),
    );

    return doc.save();
  }

  List<pw.Widget> _pdfSection(String title, List<String> items) {
    if (items.isEmpty) return const [];
    return [
      pw.Text(title, style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
      pw.SizedBox(height: 4),
      for (final item in items) pw.Bullet(text: item),
      pw.SizedBox(height: 12),
    ];
  }

  String _formatDate(DateTime date) {
    const months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'];
    return '${months[date.month - 1]} ${date.day}, ${date.year}';
  }

  Future<File> _writeToTempFile(String name, String content) async {
    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/$name');
    return file.writeAsString(content);
  }

  Future<File> _writeBytesToTempFile(String name, Uint8List bytes) async {
    final dir = await getTemporaryDirectory();
    final file = File('${dir.path}/$name');
    return file.writeAsBytes(bytes);
  }
}
